```{=html}
<style>
  body{text-align: justify}
</style>
```
::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

# **Metodologia**

Será apresnetado os aspectos principais de uma pesquisa eleitoral, levando em conta o **Plano Amostral** com base na teoria geral de estimação.

## Delineamento da Pesquisa

1.  **Tipo da Pesquisa**: pesquisa de opinião pública, do tipo quantitativo, que consiste na realização de entrevistas pessoais, com aplicação de questionário estruturado junto a uma amostra representativa do eleitorado no município de Marituba tomado como universo da pesquisa.

2.  **Objetivo da Pesquisa**: é levantar junto à população de eleitores na cidade de Marituba a intensão de votos para o próximo pleito eleitoral para Prefeitura.

3.  **Público Alvo**: Eleitores com 16 anos ou mais aptos a participarem do pleito eleitoral de 2020, com domicílio eleitoral na cidade de Marituba.

4.  **Área Física**: Município de Marituba, concentrado em 18 bairros e 33 pontos de abordagem sorteados aleatoriamente, com base nos locais de moradia, votação e pontos estratégicos, respeitando os conglomerados urbanos e rurais.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

## Amostragem

1.  **Tamanho da Amostra**: a amostra é composta por 620 eleitores entrevistados (tabela 1), tomando como base 78.803 eleitores conforme divulgação do TSE em agosto/2020.

2.  **Método de Amostragem**: Amostragem Aleatória Estratificada Proporcional ao Tamanho: Área Geográfica, Sexo, Idade, Grau de Instrução e Nível Socioeconômico, de acordo com os dados do TSE (eleitorado agosto/2020).

3.  **Ponderação dos Estratos Amostrais**: os respondentes serão selecionados através de quotas amostrais proporcionais dos estratos reconhecidos pelo TSE (Agosto/2019) em função das variáveis, agrupando-as conforme a natureza do levantamento: Sexo: masculino, 47%, feminino 53%; Idade: 16 a 24 anos, 18,7%, 25 a 34 anos: 24,5%, 35 a 44 anos: 23,3%, 45 a 59 anos: 22,5% e 60 anos ou mais: 11%; Grau de Instrução: sem escolaridades: 1,3%; Ensino Fundamental: 35,3%, Ensino Médio: 50,5%, Ensino Superior: 9%.

4.  **Margem de Erro**: O nível de confiança estimado é de 95% e a margem de erro máxima estimada considerando um modelo de amostragem aleatória estratificada, é de 5% para mais ou para menos sobre os resultados encontrados no total da amostra.

5.  **Fonte dos Dados**: número de eleitores conforme divulgação do TSE em agosto de 2020, combinado com os dados do CENSO 2010 e PNAD 2016.

6.  **Pesquisadores de Campo**: os pesquisadores e supervisores de campo contratados para aplicação dos formulários desta pesquisa foram treinados pela equipe técnica com instrução adequadas para atingir a meta e o objetivo do cliente.

7.  **Delimitação do Bairro**: dados

|   Nº  |      Bairros    | Nº Votação | Nº de Eleitores |    %   | Amostra |
|:----: |  :----:         |    :----:  |     :----:      | :----: | :----:  |
|   1   |  Centro         |  45        |   15.590        | 20.04% |  124    |
|   2   |  Decouville     |  44        |   15.596        | 20.04% |  124    |
|   3   |  Almir Gabriel  |  26        |   7.793         | 10.02% |   62    |
|   4   |  Mirizal        |  16        |    5.491        |  7.06% |   44    |
|   5   |  São Francisco  |  15        |    5.132        |  6.60% |   41    |
|   6   |  Dom Aristides  |  12        |    4.560        |  5.86% |   36    |
|   7   |  Novo           |  10        |    3.966        |  5,10% |   44    |
|   8   |  Pedreirinha    |  12        |    3.836        |  4,93% |   41    |
|   9   |  Novo Horizonte |  10        |    3.549        |  4,56% |   28    |
|  10   |  Pato Macho     |  8         |    2.584        |  3,32% |   21    |
|  11   |  São José       |  8         |    2.510        |  3.23% |   20    |
|  12   |  Uriboca        |  6         |    2.160        |  2.78% |   17    |
|  13   |  Nova União     |  5         |    1.586        |  2.04% |   13    |
|  14   |  Riacho Doce    |  3         |    1.192        |  1.53% |   09    |
|  15   |  Colônia        |  4         |      818        |  1.05  |   07    |
|  16   |  Bela Vista     |  2         |      440        |  0.57% |   04    |
|  17   |  Parque Verde   |  3         |      854        |  1.1%  |   07    |
|  18   |  Santa Clara    |  1         |      153        |  0.2%  |   01    |
| Total |   TOTAL         |  230       |    77.810       |  100   |   620   |

: Locais de Votação, por Bairros no Município de Marituba.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
